apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-fwdays-2018
  labels:
    app: dotnet-fwdays-2018
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-fwdays-2018
  template:
    metadata:
      labels:
        app: dotnet-fwdays-2018
    spec:
      containers:
      - name: dotnet-fwdays-2018
        image: mac2000/dotnet-fwdays-2018
        ports:
        - containerPort: 80
