apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-fwdays-2018
  labels:
    app: dotnet-fwdays-2018
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-fwdays-2018
  template:
    metadata:
      labels:
        app: dotnet-fwdays-2018
    spec:
      containers:
      - name: dotnet-fwdays-2018
        image: mac2000/dotnet-fwdays-2018
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
